In [148]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, PowerTransformer
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import (
    accuracy_score, 
    recall_score, 
    f1_score, 
    confusion_matrix, 
    classification_report
)
from imblearn.over_sampling import SMOTE
import warnings
warnings.filterwarnings('ignore')

In [149]:
df = pd.read_csv("../Data/preprocessed.csv")
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,OnlineSecurity,OnlineBackup,DeviceProtection,...,PaperlessBilling,MonthlyCharges,TotalCharges,Churn,Average,InternetService_Fiber optic,InternetService_No,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,0,1,0,1,0,0,0,1,0,...,1,29.85,29.85,0,29.850000,0,0,0,1,0
1,1,0,0,0,34,1,0,1,0,1,...,0,56.95,1889.50,0,55.573529,0,0,0,0,1
2,1,0,0,0,2,1,0,1,1,0,...,1,53.85,108.15,1,54.075000,0,0,0,0,1
3,1,0,0,0,45,0,0,1,0,1,...,0,42.30,1840.75,0,40.905556,0,0,0,0,0
4,0,0,0,0,2,1,0,0,0,0,...,1,70.70,151.65,1,75.825000,1,0,0,1,0


In [150]:
x = df.drop(['Churn'], axis=1)
y = df[['Churn']]

In [151]:
x1 = x.copy()
y1 = y.copy()
x2 = x.copy()
y2 = y.copy()

In [152]:
xtrain, xtest, ytrain, ytest = train_test_split(
    x, y, 
    random_state=42,
    test_size=0.2 
)

In [153]:
xtrain_no_scale = xtrain.copy()
ytrain_no_scale = ytrain.copy()

In [154]:
smote = SMOTE(random_state=42)
xtrain_no_scale_res, ytrain_no_scale_res = smote.fit_resample(xtrain_no_scale, ytrain_no_scale)

# Applying without Scalling

In [155]:
algorithms = {
    "LogisticRegression": LogisticRegression(),
    "KNeighborsClassifier": KNeighborsClassifier(),
    "RandomForestClassifier": RandomForestClassifier(),
    "XGBClassifier": XGBClassifier(),
    "GaussianNB": GaussianNB()
}

In [156]:
for model_name, models in algorithms.items():
    print(model_name)
    model = models.fit(xtrain_no_scale_res, ytrain_no_scale_res)
    print(f"Train Score: {model.score(xtrain_no_scale_res, ytrain_no_scale_res)}")
    print(f"Test Score: {model.score(xtest, ytest)}")
    pred = model.predict(xtest)
    print(f"confusion_matrix:\n{confusion_matrix(ytest, pred)}")
    print(f"accuracy_score: {accuracy_score(ytest, pred)}")
    print(f"recall_score: {recall_score(ytest, pred)}")
    print(f"f1_score: {f1_score(ytest, pred)}")
    print("____________________")
    

LogisticRegression
Train Score: 0.8181598062953995
Test Score: 0.7505330490405118
confusion_matrix:
[[798 235]
 [116 258]]
accuracy_score: 0.7505330490405118
recall_score: 0.6898395721925134
f1_score: 0.5951557093425606
____________________
KNeighborsClassifier
Train Score: 0.8427360774818402
Test Score: 0.6886993603411514
confusion_matrix:
[[734 299]
 [139 235]]
accuracy_score: 0.6886993603411514
recall_score: 0.6283422459893048
f1_score: 0.5176211453744494
____________________
RandomForestClassifier
Train Score: 0.9984261501210654
Test Score: 0.7640369580668088
confusion_matrix:
[[854 179]
 [153 221]]
accuracy_score: 0.7640369580668088
recall_score: 0.5909090909090909
f1_score: 0.5710594315245479
____________________
XGBClassifier
Train Score: 0.9645278450363196
Test Score: 0.7469793887704336
confusion_matrix:
[[837 196]
 [160 214]]
accuracy_score: 0.7469793887704336
recall_score: 0.5721925133689839
f1_score: 0.5459183673469388
____________________
GaussianNB
Train Score: 0.800363196

# Apply with Scaling

In [157]:
scale_xtrain = xtrain.copy()
scale_xtest = xtest.copy()

In [158]:
sts = StandardScaler()
sel_col = ['tenure', 'MonthlyCharges', 'TotalCharges', 'Average']
scale_xtrain[sel_col] = sts.fit_transform(scale_xtrain[sel_col])
scale_xtest[sel_col] = sts.transform(scale_xtest[sel_col])

In [159]:
smote = SMOTE(random_state=42)
scale_xtrain_res, scale_ytrain_res = smote.fit_resample(scale_xtrain, ytrain)

In [160]:
for model_name, models in algorithms.items():
    print(model_name)
    model1 = models.fit(scale_xtrain_res, scale_ytrain_res)
    print(f"Train Score: {model1.score(scale_xtrain_res, scale_ytrain_res)}")
    print(f"Test Score: {model1.score(scale_xtest, ytest)}")
    pred1 = model1.predict(scale_xtest)
    print(f"confusion_matrix:\n{confusion_matrix(ytest, pred1)}")
    print(f"accuracy_score: {accuracy_score(ytest, pred1)}")
    print(f"recall_score: {recall_score(ytest, pred1)}")
    print(f"f1_score: {f1_score(ytest, pred1)}")
    print("____________________")

LogisticRegression
Train Score: 0.8035108958837772
Test Score: 0.744136460554371
confusion_matrix:
[[778 255]
 [105 269]]
accuracy_score: 0.744136460554371
recall_score: 0.7192513368983957
f1_score: 0.5991091314031181
____________________
KNeighborsClassifier
Train Score: 0.8671912832929782
Test Score: 0.7000710732054015
confusion_matrix:
[[718 315]
 [107 267]]
accuracy_score: 0.7000710732054015
recall_score: 0.713903743315508
f1_score: 0.5585774058577406
____________________
RandomForestClassifier
Train Score: 0.9984261501210654
Test Score: 0.7697228144989339
confusion_matrix:
[[847 186]
 [138 236]]
accuracy_score: 0.7697228144989339
recall_score: 0.6310160427807486
f1_score: 0.592964824120603
____________________
XGBClassifier
Train Score: 0.9548426150121065
Test Score: 0.7533759772565742
confusion_matrix:
[[820 213]
 [134 240]]
accuracy_score: 0.7533759772565742
recall_score: 0.6417112299465241
f1_score: 0.5804111245465539
____________________
GaussianNB
Train Score: 0.7717917675544

In [161]:
skewness = xtrain.skew()
print(skewness)

gender                                  -0.027388
SeniorCitizen                            1.848148
Partner                                  0.076521
Dependents                               0.876341
tenure                                   0.242015
PhoneService                            -2.712560
MultipleLines                            0.337224
OnlineSecurity                           0.939456
OnlineBackup                             0.645379
DeviceProtection                         0.662774
TechSupport                              0.927032
StreamingTV                              0.469424
StreamingMovies                          0.445621
Contract                                 0.629932
PaperlessBilling                        -0.371497
MonthlyCharges                          -0.217908
TotalCharges                             0.969682
Average                                 -0.207431
InternetService_Fiber optic              0.243993
InternetService_No                       1.357853


In [162]:
skewed_freature = skewness[abs(skewness) > .5]
print(f"Skewed_freature:\n{skewed_freature}")

Skewed_freature:
SeniorCitizen                            1.848148
Dependents                               0.876341
PhoneService                            -2.712560
OnlineSecurity                           0.939456
OnlineBackup                             0.645379
DeviceProtection                         0.662774
TechSupport                              0.927032
Contract                                 0.629932
TotalCharges                             0.969682
InternetService_No                       1.357853
PaymentMethod_Credit card (automatic)    1.367934
PaymentMethod_Electronic check           0.684501
PaymentMethod_Mailed check               1.279641
dtype: float64


In [183]:
skew_xtrain = xtrain.copy()
skew_xtest = xtest.copy()

In [191]:
pt = PowerTransformer(method='yeo-johnson')
sel_skew = skewed_freature.index

skew_xtrain[sel_skew] = pt.fit_transform(skew_xtrain[sel_skew])
skew_xtest[sel_skew] = pt.transform(skew_xtest[sel_skew])

In [192]:
xtrain_skewed_scaled_res, ytrain_skewed_scaled_res = smote.fit_resample(skew_xtrain, ytrain)

In [ ]:
gnb = GaussianNB()
gnb_param_grid = {
    'var_smoothing': [1e-12, 1e-10, 1e-9, 1e-8, 1e-7, 1e-6, 1e-5]
}

gnb_grid = GridSearchCV(
    estimator=gnb, param_grid=gnb_param_grid, cv = 10, scoring='f1'
)
gnb_model = gnb_grid.fit(xtrain_skewed_scaled_res, ytrain_skewed_scaled_res)

In [195]:
print(f"Train score: {gnb_model.score(xtrain_skewed_scaled_res, ytrain_skewed_scaled_res)}")
print(f"Test score: {gnb_model.score(skew_xtest, ytest)}")
gnb_pred = gnb_model.predict(skew_xtest)
print(f"Accuracy Score: {accuracy_score(ytest, gnb_pred)}")
print(f"Recall Score: {recall_score(ytest, gnb_pred)}")
print(f"f1 Score: {f1_score(ytest, gnb_pred)}")
print(f"confussion matrix:\n{confusion_matrix(ytest, gnb_pred)}")
print(f"Best Parameter: {gnb_model.best_params_}")
print(f'Best Score: {gnb_model.best_score_}')

Train score: 0.777299880525687
Test score: 0.6072961373390557
Accuracy Score: 0.7398720682302772
Recall Score: 0.7566844919786097
f1 Score: 0.6072961373390557
confussion matrix:
[[758 275]
 [ 91 283]]
Best Parameter: {'var_smoothing': 1e-12}
Best Score: 0.7748426627002678


Not good performance so we are trying logistic regession

In [197]:
logi = LogisticRegression(max_iter=500)
log_param_grid = {
    'C': [0.01, 0.1, 1, 5, 10, 50],
    'penalty': ['l1', 'l2'],
    'solver': ['liblinear'],
    'class_weight': [None, 'balanced']
}
logistic_grid = GridSearchCV(
    estimator=logi,
    param_grid=log_param_grid,
    cv= 5, 
    scoring='f1',
    n_jobs=-1
)
logistic_model = logistic_grid.fit(scale_xtrain_res, scale_ytrain_res)
print(f"Train Score: {logistic_model.score(scale_xtrain_res, scale_ytrain_res)}")
print(f"Test Score: {logistic_model.score(scale_xtest, ytest)}")
logistic_pred = logistic_model.predict(scale_xtest)
print(f"confusion_matrix:\n{confusion_matrix(ytest, logistic_pred)}")
print(f"accuracy_score: {accuracy_score(ytest, logistic_pred)}")
print(f"recall_score: {recall_score(ytest, logistic_pred)}")
print(f"f1_score: {f1_score(ytest, logistic_pred)}")

Train Score: 0.8122076707202993
Test Score: 0.6
confusion_matrix:
[[784 249]
 [107 267]]
accuracy_score: 0.7469793887704336
recall_score: 0.713903743315508
f1_score: 0.6
